### ISSUE TITLE
r.relations and adding extra relationships

### ISSUE THREAD

**Issue by randomiser** [IlyaSemenov/graphql-orm#33]
Hi there,

I've just recently upgraded from 5 -> 7 using the objection variant.

Everything seems to be going really well apart from one small change that I had to make:

I have a few examples of the following in my codebase:

```
 // Select all objects in -to-many relation
comments: true,
// Select all objects in -to-many relation
all_comments: r.relation({
          modelField: "comments",
         .... etc
```

When I attempted to query this relationship I get the following error:

```
query ($id: ID!) {
    post(id: $id {
       all_comments {
           ...
       }
    } 
}

```
```
[15:56:39.676] ERROR (52345): unknown relation "all_comments" in an eager expression
    err: {
      "type": "GraphQLError",
      "message": "unknown relation \"all_comments\" in an eager expression",
      "stack": ...

```

To get around this I had to explicitly add "all_comments" as a **new relationship** to my model:

```
class Post extends Model {

static get relationMappings() {
    return {
       comments: ...,
       all_comments: ...,
    }
}
```
After making the above change it worked again as expected. I've not had to do that previously so I'm assuming it is a minor bug.

My versions are:

├── objection-graphql-resolver@7.2.1
├── objection@3.1.2

Thanks for any help with this.

Kind regards,
Matt

**Comment by IlyaSemenov** [comment]
Thank you for report! I renamed the respective base field to `tableField` when extracting the common core to reuse with orchid-graphql, but failed to update the documentation properly.

I've just added support for both `tableField` and `modelField` so that the legacy code could continue to work as is.

**Comment by randomiser** [comment]
Ok great thanks for the quick response! The main documentation still refers to modelField btw:

https://github.com/IlyaSemenov/graphql-orm/tree/master/packages/objection-graphql-resolver

**Comment by IlyaSemenov** [comment]
Right, because now `modelField` is internally an alias for `tableField` and is fully supported. Objection uses the term 'model' so I figured it's reasonable to continue to have this wording in the options. This is actually the main architectural difference between Objection and Orchid, the former uses ActiveRecord-style model objects, and the latter deliberately returns typed POJO's.

**Comment by randomiser** [comment]
Ah ok, makes sense. 

I like the way you've made the api more consistent with renaming modifier/select etc. Makes it way easier to use.
